# TODO
# Implement light-weight version of the image using lighter node

FROM node:20-alpine

RUN apk add --no-cache bash make python3 g++ 

WORKDIR /app

COPY app/package*.json ./

RUN npm ci

COPY app/ .

RUN rm -f database.sqlite

ENV FASTIFY_ADDRESS=0.0.0.0
EXPOSE 8080

CMD ["make", "test"]
